* cl-web-utils README
cl-web-utils was originally styled as cl-web-apis and written by Will
Halliburton. The goal is to eliminate as much repitition from binding
to web APIs as possible through judicious use of macros and a variety
of other lisp niceties. We borrow heavily from existing and
established lisp code where possible ranging from drakma, cxml and
cl-json to bits of anaphora, metatilities and even a few symbol
building functions from On Lisp.

It's a pretty straightforward library with a chief emphasis on the
functions define-json-request and define-xml-request and a smattering
of other helpers. They are the chief exports of the cl-web-utils
package. Other small niceties from the stylistic (concat ...) as an
abbreviation of (concatenate 'string ...) to slightly more intuitive
stdlib functions (last1 ...) in lieu of (car (last ...)) and others
like (parse-float ...) and (md5 ...).

* Dependencies
Check out cl-web-utils.asd for the list of dependencies.

* Tasks
** TODO Write a readme
** TODO Post a library with example usage
** TODO Blog post about the library
** TODO Docstrings for every function
** TODO Add Alexandria dependency
